#spring:
#  profiles:
#    active: dev

server:
  port: ${PORT:8080}

keycloak:
  auth-server-url: https://apollon-music-keycloak.herokuapp.com/auth
  realm: "apollon-music"
  resource: "resource-server"
  bearer-only: true
  security-constraints:
    - authRoles:
        - uma_authorization # authenticated users only
      securityCollections:
        - patterns:
            - /api/*

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
