server:
  port: ${PORT:8080}

keycloak:
  auth-server-url: https://apollon-music-keycloak.herokuapp.com/auth
  realm: "apollon-music"
  resource: "resource-server-prod"
  bearer-only: true

  securityConstraints:
    - authRoles: [ uma_authorization ]
      securityCollections:
        - name: API Private Data
          patterns: [ '/api/*' ]
    - authRoles: [ ADMIN ]
      securityCollections:
        - name: ADMIN API
          patterns: [ '/admin/api/*' ]

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

limit:
  track:
    max-count: 10